/*console.log("hello world")
const mot = "hellow world"
console.log("mot: ",mot)
let nombre = 7
console.log("nombre: ",nombre)
let bloolean = true
let nom = "bouzerar"
let prenom = "sonia"
console.log(nom+""+prenom)
let a=2
let b=4
console.log(a+b+nom+prenom)
console.log (nom+prenom+(a+b))
console.log(a  + prenom + b + a + b*a) 

//3.Alert, promt & confirm
alert("This is an alert")
let VisitorName = prompt("what's your name :")
console.log(VisitorName)

let confirmation = confirm("Are you okay wiyh is?")
console.log(confirmation)

//4.Operators
console.log(4 + 2)
console.log(4 - 2)
console.log(4 * 2)
console.log(4 / 2)
// Modulo: Reste de division
console.log(10 % 3)
// puissance
console.log(4 ** 2)
// console.log(0 / 0)
//5. Comparaisons
let firstNumber = 4
let secondNumber = 2
let x = firstNumber >= secondNumber // true
let y = firstNumber <= secondNumber // false
console.log("a = " ,x) 
console.log("b =",y)*/
//==egalite des valeurs et === egalite des valeurs= leurs type
/*let firstNumber = 4
let secondNumber = "4"
let result = firstNumber!==secondNumber
console.log("result= ",result)

let inc = 0
inc++ //inc = inc +1
console.log("inc :",inc)
inc--//inc = inc-1
console.log("inc :",inc)

let t = 5
let v = 2
console.log("t:",t)
t += V //t = t */

/*//6.Operateurs logiques
let x = 1 // true
let y = 0 // false
console.log("x: ",x)
console.log("y :",y)
//Arrays
let valeursNumeriques = {1,2,3,4,5}
console.log(typeof(valeursNUMERIQUES))
console.log(valeursNumeriques{2})
console.log(valeursNumeriques{4})
let Names ={"Ali","Ilyes","Fatima","Yakout","Fayza"}
console.log(Names{1})

//Objects
let persone ={
    persone:"Ali",
    age:50,
    enfants:{"Fres","Lilia"}
}
console.log(person.age)
person.nom = "nom" 
//console.log("tab1 is",valeurs)
let days ={"Monday","Tuesday", "Wensday","thursday"}
console.log("Days: ",days)
days.push("Saturday") //add element at the end
console.log("Days:",Days)
days.wshift("Sunday") // add element at the beginin
console.log("Days:",Days)
Days.pop()
console.log("after pop Days:" ,Days)
Days.shift()
console.log('After shift Days:',Days)*/

/*// definition d'une fonction add
Fonction add (a,b){
    let result = a + b
    return result
}
console.log(add(4,5)) //Appel a la fonction*/
 //Arrow function
 const add = (a,b) => {
    let result = a + b
    return result
 }
 a = 5 
 b = 6
 console.log(add(a,b))
